/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jeans.panels;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import jeans.config;
import jeans.Produk;
import jeans.dialog.AddNewProduk;
import jeans.dialog.EditProduk;
import jeans.dialog.HapusProduk;

/**
 *
 * @author acer
 */
public class ManageProduk extends javax.swing.JPanel {
    Produk Pk;

    /**
     * Creates new form ManageProduk
     */
    public ManageProduk() {
        initComponents();
        
        RefreshData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnAddNewProduk = new javax.swing.JButton();
        btnEditProduk = new javax.swing.JButton();
        btnHapusProduk = new javax.swing.JButton();
        btnRefreshProduk = new javax.swing.JButton();
        btnCariProduk = new javax.swing.JButton();
        txtPencarian = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(229, 247, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Produk", "Nama Produk", "Harga", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(229, 247, 255));

        btnAddNewProduk.setText("Tambah");
        btnAddNewProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewProdukActionPerformed(evt);
            }
        });

        btnEditProduk.setText("Edit");
        btnEditProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProdukActionPerformed(evt);
            }
        });

        btnHapusProduk.setText("Hapus");
        btnHapusProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusProdukActionPerformed(evt);
            }
        });

        btnRefreshProduk.setText("Refresh");
        btnRefreshProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshProdukActionPerformed(evt);
            }
        });

        btnCariProduk.setText("Cari");
        btnCariProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariProdukActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnAddNewProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapusProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefreshProduk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCariProduk)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCariProduk)
                            .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddNewProduk)
                            .addComponent(btnEditProduk)
                            .addComponent(btnHapusProduk)
                            .addComponent(btnRefreshProduk))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCariProdukActionPerformed

    private void btnAddNewProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewProdukActionPerformed
        // TODO add your handling code here:
        AddNewProduk USK = new AddNewProduk(null, true);
        USK.setVisible(true);
    }//GEN-LAST:event_btnAddNewProdukActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int n = jTable1.getSelectedRow();
        if(n != -1){
            btnEditProduk.setEnabled(true);
            btnHapusProduk.setEnabled(true);
            
            //capture data
            Object IDPg = jTable1.getValueAt(n, 0);
            int ID = Integer.parseInt(IDPg.toString());        
            String produkPd = jTable1.getValueAt(n, 1).toString();
            String hargaPd = jTable1.getValueAt(n, 2).toString();
            String stockPd = jTable1.getValueAt(n, 3).toString();
            Pk = new Produk();
            Pk.setId(ID); 
            Pk.setProduk(produkPd); 
            Pk.setHarga(hargaPd);
            Pk.setStock(stockPd);
        }else {            
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnRefreshProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshProdukActionPerformed
        // TODO add your handling code here:
        btnEditProduk.setEnabled(false);
        btnHapusProduk.setEnabled(false);
        jTable1.clearSelection();
    }//GEN-LAST:event_btnRefreshProdukActionPerformed

    private void btnEditProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProdukActionPerformed
        // TODO add your handling code here:
        EditProduk Usd = new EditProduk(null, true);
        Usd.Pd = Pk;
        Usd.setVisible(true);
    }//GEN-LAST:event_btnEditProdukActionPerformed

    private void btnHapusProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusProdukActionPerformed
        // TODO add your handling code here:
        HapusProduk HD = new HapusProduk(null, true);
        HD.Dk = Pk;
        HD.setVisible(true);
    }//GEN-LAST:event_btnHapusProdukActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewProduk;
    private javax.swing.JButton btnCariProduk;
    private javax.swing.JButton btnEditProduk;
    private javax.swing.JButton btnHapusProduk;
    private javax.swing.JButton btnRefreshProduk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextField txtPencarian;
    // End of variables declaration//GEN-END:variables

public static void RefreshData(){
        try {
            jTable1.setRowHeight(30);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            
            for (int i = model.getRowCount()-1; i>=0; i--) {
                model.removeRow(i);   
            }
            
            String Q = "SELECT * FROM produk";
            Connection C = config.configDB();
            Statement S = C.createStatement();
            ResultSet R = S.executeQuery(Q);
            while (R.next()){
                int ID = R.getInt("id_produk");
                String  PRODUK = R.getString("produk");
                String HARGA = R.getString("harga");
                String STOCK = R.getString("stock");
                Object[] datausers = {ID, PRODUK, HARGA, STOCK};
                model.addRow(datausers);
            }
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
            for (int i = 0; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        } catch (Exception e){
            e.printStackTrace();
            
        }
        
    }
}
